FROM ubuntu
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
RUN echo "Hello world" > /var/www/html/index.html
WORKDIR "/var/www/html"
CMD ["apachectl","-D","FOREGROUND"]
EXPOSE 80